#######################
#                     #
#   BackPacks 1.0.0   #
#      by DevSnx      #
#                     #
#######################

backpack:
  main:
    title: '&dDeine Rucks채cke'
    itemColor: '&d'
    itemMaterial: 'CHEST'
  backpack:
    titleColor: '&b'
    changename:
      itemMaterial: 'NAME_TAG'
      itemName: '&bRucksack umbenennen'

message:
  changebackpackname:
    message: '&aBitte gib einen Namen f체r den Rucksack ein: '
    sucsees: '&7Du hast den Rucksacknamen von &e%backpackName% &7auf &b%newBackpackName% &7ge채ndert.'
    invalidCharacters: '&cDer Rucksackname darf keine Sonderzeichen enthalten. Bitte versuche es erneut.'
    nameAlreadyExists: '&cDer Rucksackname existiert bereits f체r einen anderen Rucksack. Bitte versuche es erneut.'